name: CI pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

  steps:
    - name: checkout code
      uses: actions/checout@v1

    - name: python
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'

    - name: poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -
        poetry config virtualenvs.create true
        poetry install --no-interaction --no-ansi

  steps:
    - name: run pytest
    run: |
      poetry run pytest

  steps:
    - name: run pylint
    run: |
      poetry run pylint life_expectancy